
name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Prepare Node.js 12.x
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 12.x
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: yarn install

    - name: Tests
      run: yarn test

    - name: Publish
      run: |
        npm whoami
        yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
